apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ml-ops
resources:
  - ../base/namespaces+v1/
  - ../base/iris-v1.0.0+v1/
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: iris-classifier