{{- if .Values.storage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "iris-classifier.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "iris-classifier.labels" . | nindent 4 }}
spec:
  {{- include "iris-classifier.storageConfig" . | nindent 2 }}
{{- end }}