{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "iris-classifier.fullname" . }}-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "iris-classifier.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "iris-classifier.labels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.metrics.port }}
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.interval }}
      scheme: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
