apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ml-ops
resources:
  - ../../../applications/namespace/v1/
  - ../../../applications/iris/v1.2.0+v1/
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: iris-classifier