apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress
spec:
  interval: 1m
  timeout: 3m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.0" 
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress
  install:
    remediation:
      retries: 3
  values:
    controller:
      replicaCount: 2
      service:
        type: NodePort
        externalTrafficPolicy: Local
      admissionWebhooks:
        enabled: false