apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: iris-classifier
  namespace: flux-system
spec:
  interval: 0m5s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deployment/overlays/dev
  prune: true
  wait: true