apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress
spec:
  interval: 2m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.12.2" 
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress
  values:
    controller:
      replicaCount: 2
      service:
        externalTrafficPolicy: Local
      admissionWebhooks:
        enabled: false