apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ../../../../applications/namespace/v1/
  - ../../../../applications/cert-manager/v1.17.1-v1/
# patches:
#   - path: values.yaml
#     target:
#       kind: HelmRelease
#       name: cert-manager